---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: octant
resources:
- namespace.yml
- deployment.yml
- service.yml
- ingress.yml
secretGenerator:
  - name: kubeconfig
    files:
      - kubeconfig
images:
- name: octant
  newName: alexandreroman/octant:0.16.0
